version: '3.8'

services:
  mysql:
    image: mysql:8.0.22
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306  
    environment:
      MYSQL_DATABASE: turnos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysql_data:
